// (c) Yuri N. K. 2025. All rights reserved.
// ykasczc@gmail.com

#pragma once

#include "CoreMinimal.h"
#include "NNERuntimeCPU.h"
#include "DSP/AlignedBuffer.h"
#include "LocalTTSTypes.generated.h"

//DECLARE_LOG_CATEGORY_EXTERN(LogLocalTTS, Log, All);

class UNNEModelData;
class UTTSModelData_Base;

// Helpers for android support
namespace PlatformFileUtils
{
	// Fix invalid delimiters in the path
	void NormalizePath(FString& Path);

	// Return absolute actual path on storage device from the Unreal path
	// For Windows they're equal 
	FString GetPlatformPath(FString Path);

	// Check if directory exists on physical disk
	bool DirectoryExists(const FString& Dir);
}

namespace Piper
{
	typedef char32_t PhonemeUtf8;
	typedef int64_t PhonemeId;
}

/**
* Phonemization approach (not in use)
*/
UENUM(BlueprintType)
enum class ETTSPhonemeType : uint8
{
	PT_eSpeak				UMETA(DisplayName = "eSpeak"),
	PT_Tashkeel				UMETA(DisplayName = "Tashkeel"),
	PT_Misaki				UMETA(DisplayName = "Misaki"),
	PT_TextPhoneme			UMETA(DisplayName = "Text")
};

// Container for NNM instance key in ULocalTTSSubsystem
USTRUCT(BlueprintType, meta=(DisplayName = "TTS Model Instance ID"))
struct FNNMInstanceId
{
	GENERATED_BODY()

	// Key in ULocalTTSSubsystem::VoiceModels
	UPROPERTY()
	int32 Id = INDEX_NONE;

	FNNMInstanceId() {}
	FNNMInstanceId(int32 Index) : Id(Index) {}
	FNNMInstanceId& operator=(int32 Value)
	{
		Id = Value; return *this;
	}
	bool operator==(int32 Value) const
	{
		return Id == Value;
	}
};

// NNM input index to data buffer
USTRUCT()
struct FNNEModelInputBinding
{
	GENERATED_BODY()

	// Data format in NNM input
	ENNETensorDataType Format = ENNETensorDataType::None;
	// Corresponding array index
	int32 ArrayIndex = INDEX_NONE;
};

/**
* Generic TTS ONNX model with input and output settings
*/
USTRUCT()
struct FNNEModelTTS
{
	GENERATED_BODY()

protected:
	FGuid Guid;

public:
	TObjectPtr<UTTSModelData_Base> VoiceDesc = nullptr;
	FString ModelAssetName;

	// NN Setup
	TSharedPtr<UE::NNE::IModelInstanceCPU> ModelInstance;
	TArray<UE::NNE::FTensorBindingCPU> InputBindings;
	TArray<UE::NNE::FTensorBindingCPU> OutputBindings;
	UE::NNE::FTensorShape DefaultInputShape;
	UE::NNE::FTensorShape DefaultOutputShape;

	// Universal input mapping
	// Actual piper inputs: {"input" (int64), "input_lengths" (int64), "scales" (float), [ "sid" (int64) ] }
	TArray<FNNEModelInputBinding> InputMap;
	TArray<TArray<float>> InputDataFloat;
	TArray<TArray<int64>> InputDataInt64;
	// Outputs
	TArray<float> OutputData;

	bool bLoaded = false;

	FNNEModelTTS() : Guid(FGuid::NewGuid()) {}

	bool operator==(const FNNEModelTTS& Other) const
	{
		return Guid == Other.Guid;
	}

	FString GetGUID() const { return Guid.ToString(); }

	TArray<int64>& GetInParamIntUnsafe(const int32 Index);
	TArray<float>& GetInParamFloatUnsafe(const int32 Index);
	bool CheckInParam(const int32 Index, ENNETensorDataType Type) const;
};

/**
* Non-static text-to-speech generation settings
*/
USTRUCT(Blueprintable)
struct FTTSGenerateSettings
{
	GENERATED_BODY()

	// Numeric ID of speaker in the model. Use -1 for models without speakers map.
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "TTS Generate Settings")
	int32 SpeakerId = INDEX_NONE;
};

/**
* Model parameters; internal; used to fill NNM inputs
*/
USTRUCT()
struct FTTSGenerateRequestContext
{
	GENERATED_BODY()

	// ID of speaker in the model
	UPROPERTY()
	int32 SpeakerId = INDEX_NONE;

	// Pointer to tokens
	const TArray<Piper::PhonemeId>* Tokens = nullptr;
};

/**
* All data generated by NNM
*/
USTRUCT()
struct FSynthesisResult
{
	GENERATED_BODY()

	// Voice
	FNNMInstanceId ModelTag;

	// Phonemized input data
	TArray<TArray<Piper::PhonemeUtf8>> PhonemePhrases;

	// Generated audio duration
	double AudioSeconds = 0.0;

	// Final post-processed sample rate of PCMData32 and PCMData16
	int32 SampleRate = 0;

	// Primary audio buffer (32-bit)
	Audio::FAlignedFloatBuffer PCMData32;
	// Buffer converted to 16-bit format
	TArray<uint8> PCMData16;

	void Reset(const FNNMInstanceId& NewVoice)
	{
		ModelTag = NewVoice;
		AudioSeconds = 0.f;
		PCMData16.Empty();
		PhonemePhrases.Empty();
	}
};
